services:
  fastapi-container:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - fastapi_data:/app/data
    restart: unless-stopped

volumes:
  fastapi_data: